[package]
name = "bitfield-impl"
version = "0.0.0"
edition = "2018"
publish = false

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.10"
syn = {version="1.0.17", features=["full", "extra-traits"]}
quote = "1.0.3"
